### ISSUE TITLE
Rest-Client 1.8 is incompatible with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by ushis** [sensu-plugins/sensu-plugins-http#81]
Rest-Client 1.8 is incompatible with OpenSSL 1.1.0. See:

- https://github.com/rest-client/rest-client/pull/573
- https://github.com/rest-client/rest-client/issues/569

This makes metrics-http-json.rb unusable on machines with OpenSSL 1.1.0. Please update the rest-client dependency to 2.0.2

**Comment by majormoses** [comment]
@ushis thanks for reporting, any chance you might be able to submit a PR for this?

**Comment by ushis** [comment]
@majormoses done https://github.com/sensu-plugins/sensu-plugins-http/pull/83

**Comment by majormoses** [comment]
@ushis I have commented, basically as proposed this breaks ruby 2.1 support which is a supported version so that needs to be addressed. If we can not figure out how to keep ruby 2.1 we will discuss the implications and make a decision on what to do but I would like us to first explore the option to avoid breaking changes.
